DROP VIEW PERSISTENTES.Ticket_Promedio_Mensual
DROP TABLE PERSISTENTES.hechos_ventas
DROP TABLE PERSISTENTES.DI_tiempo
DROP TABLE PERSISTENTES.DI_rangoEtario
DROP TABLE PERSISTENTES.DI_ubicacion
DROP TABLE PERSISTENTES.DI_turno
DROP TABLE PERSISTENTES.DI_tipoCaja





