use GD1C2024
DROP VIEW PERSISTENTES.Cantidad_Unidades_Promedio
DROP VIEW PERSISTENTES.Ticket_Promedio_Mensual
DROP TABLE PERSISTENTES.hechos_ventas
DROP TABLE PERSISTENTES.BI_tiempo
DROP TABLE PERSISTENTES.BI_rangoEtario
DROP TABLE PERSISTENTES.BI_ubicacion
DROP TABLE PERSISTENTES.BI_turno
DROP TABLE PERSISTENTES.BI_tipoCaja





